### ISSUE TITLE
validyaml doesn`t work in Azure DevOps agents

### ISSUE THREAD

**Issue by AliakseiVenski** [martinlindhe/validyaml#1] opened 2021-04-09 17:03 UTC
I tried to use it in Azure DevOps pipeline powershell task to validate files in the job, but validyaml always says that it is OK.
Even if you`ll specify file that doesn`t exist at all - it will be OK.

Steps to reproduce:
Run Powershell task in any windows  self-hosted or Azure-Pipelines-hosted agent which will call 32\64 bit validyaml.exe for file validating.

**Comment by martinlindhe** [comment] 2021-04-10 21:37
Please show how you are invoking the command. I can not reproduce any issue with piping data in powershell.

**Comment by AliakseiVenski** [comment] 2021-04-12 09:04
I`m invoking it like this: "validyaml.exe file.yml" - it will behave as I mentioned above.
And yes, if you pipe file content to the tool - it will work: Get-Content file.yml | validyaml.exe

So please check it without piping.

**Comment by martinlindhe** [comment] 2021-04-12 09:40
> I`m invoking it like this: "validyaml.exe file.yml" - it will behave as I mentioned above.
> And yes, if you pipe file content to the tool - it will work: Get-Content file.yml | validyaml.exe
> 
> So please check it without piping.

Invoked without piped data or file input should give you the following:

```
$ validyaml
error: no piped data and no file provided
```

I am not sure what you are trying to report here.
You write that the two possible  ways of invocation works correctly, so what is your issue?

**Comment by AliakseiVenski** [comment] 2021-04-12 10:13
Example 1:
validyaml.exe file.yml - doesn`t work (try to point to file with error, it won`t report it)
Example 2:
get-content file.yml | validyaml.exe - works

This is what I`m reporting. To reproduce please create powershell task in pipeline, so this is the only place where it doesn`t work. And it doesn`t matter will it be ps1 file or inline script.

**Comment by martinlindhe** [comment] 2021-04-12 10:31
> Example 1:
> validyaml.exe file.yml - doesn`t work (try to point to file with error, it won`t report it)

For all tests I have done, this does indeed work correctly. If you can provide any invalid yaml file that the project claims is valid, then please attach them to this issue.

You can verify yourself the program is working correctly with the example files in https://github.com/martinlindhe/validyaml/tree/master/examples


> This is what I`m reporting. To reproduce please create powershell task in pipeline, so this is the only place where it doesn`t work. And it doesn`t matter will it be ps1 file or inline script.

Please understand that this is free software that I have developed on my spare time. I will not set up azure pipelines to help you with your day job.

If you want this issue "fixed", then you must provide beyond reasonable doubt that my software is actually at fault, and a way to reproduce it.

**Comment by AliakseiVenski** [comment] 2021-04-12 11:13
I just used your "bad" file example, there is script I invoked in powershell job:

"list:

one
" | Out-File $PSScriptRoot\bad.yaml

$Repo = "https://api.github.com/repos/martinlindhe/validyaml/releases"

$Url = ((Invoke-RestMethod $Repo)[0].assets | Where-Object { $_.name -match "windows_64-bit.zip" }).browser_download_url

$FileName = $Url.Split("/")[-1]
$FilePath = "$PSScriptRoot\$FileName"

Write-Output "Dowloading latest release"
Invoke-RestMethod -Uri $Url -OutFile $FilePath

Write-Output "Extracting release files"
Expand-Archive -LiteralPath $FilePath -DestinationPath "$PSScriptRoot\validyaml\" -Force
Remove-Item -LiteralPath $FilePath -Force
& $PSScriptRoot\validyaml\validyaml.exe $PSScriptRoot\bad.yaml

**Comment by AliakseiVenski** [comment] 2021-04-12 11:14
And there is the result:
![image](https://user-images.githubusercontent.com/36035128/114386008-5d25ec00-9b99-11eb-8b13-0b0050f061ce.png)

**Comment by AliakseiVenski** [comment] 2021-04-12 11:15
It`s ok if you won`t resolve this, but it exists, I just want to share it with you. Anyways - option  with get-content works.

**Comment by martinlindhe** [comment] 2021-04-12 12:44
No part of the code you supply proves to me that the content of the file "bad1.yml" on your system contains invalid yaml.
You are only showing how you download and extract the zip archive.

I will close this issue since it appears to me it is user error.

**Closed as completed by martinlindhe** 2021-04-12 12:44 UTC

**Comment by martinlindhe** [comment] 2021-04-12 12:45
Glad you figured it out.
